### ISSUE TITLE
about Image captioning task code

### ISSUE THREAD

**Issue by wanboyang** [yangxuntu/lxmertcatt#2]
Thanks for your opening sources.
I do not find codes of  CATT for Image captioning task.
Will you update this project for COCO Image captioning task?

**Comment by yangxuntu** [comment]
I think it is not hard to implement this model after I give LXMERT+CATT. And I am still on leave recently.
________________________________
发件人: wanboyang ***@***.***>
发送时间: 2021年5月9日 17:32
收件人: yangxuntu/lxmertcatt ***@***.***>
抄送: Subscribed ***@***.***>
主题: [yangxuntu/lxmertcatt] about Image captioning task code (#2)


Thanks for your opening sources.
I do not find codes of CATT for Image captioning task.
Will you update this project for COCO Image captioning task?

―

**Comment by wanboyang** [comment]
Thanks for timely replying
